#!/usr/bin/python3
"""
CLI script for storing serial numbers generated by functions in serial.py to a SQL databse.
"""

import os
import sqlite3

def test_for_database(db_name):
    return os.path.exists(db_name)
    
def create_database(db_name):
    if os.path.splitext(db_name)[1] != '.db':
        print('Name has to end with ".db".')
        return False
        #TODO: replace this branch with an error and a try/except(?)
    if not test_for_database(db_name):
        conn = sqlite3.connect(db_name)
        cur = conn.cursor()
        cur.execute('''create table prototypes (index, serial_number, name)''')
        cur.execute('''create table components (index, serial_number, name)''')
        cur.execute('''create table experiments (index, serial_number, name) ''')
        cur.commit()
        conn.close()
        print('Database created successfully')
    else:
        print('Database already exists')