#!/usr/bin/python3
"""
CLI script for storing serial numbers generated by functions in serial.py to a SQL databse.
"""

import os
import sqlite3


def test_for_database(db_name):
    return os.path.exists(db_name)

    
def create_database(db_name):
    if os.path.splitext(db_name)[1] != '.db':
        print('Name has to end with ".db".')
        return False
        #TODO: replace this branch with an error and a try/except(?)
    if not test_for_database(db_name):
        conn = sqlite3.connect(db_name)
        cur = conn.cursor()
        cur.execute('''create table prototypes 
                    (index integer primary key, 
                     serial_number varchar(25) not null,
                     name varchar(50))''')
        cur.execute('''create table components 
                    (index integer primary key, 
                     serial_number varchar(25) not null, 
                     name varchar(50)''')
        cur.execute('''create table experiments 
                    (index integer primary key, 
                     serial_number varchar(25) not null, 
                     name varchar(50) ''')
        cur.commit()
        conn.close()
        print('Database created successfully')
    else:
        print('Database already exists')


def delete_database(db_name):
    if test_for_databse(db_name) and os.path.splitext(db_name)[1] == '.db':
        os.remove(db_name)
        print('Database {} removed.'.format(db_name))
    else:
        print('Can only be used to remove db files.')


def add_record(db_name, serial_type, serial_number, name=''):
    if not test_for_database(db_name):
        create_databse(db_name)
    conn = sqlite3.connect(db_name)
    cur = conn.cursor()
    if serial_type == 'prototype':
        cur.execute('insert into prototypes(serial_number, name) values (?, ?)', (serial_number, name))
    elif serial_type == 'component':
        cur.execute('insert into components(serial_number, name) values (?, ?)', (serial_number, name))
    elif serial_type == 'experiment':
        cur.execute('insert into experiments(serial_number, name) values (?, ?)', (serial_number, name))
    cur.commit()
    curr.close()
    print('Record added')
    
    
def delete_record(db_name, serial_type, serial_number):
    if test_for_database(db_name):
        conn = sqlite3.connect(db_name)
        cur = con.cursor()
        if serial_type == 'prototype':
            cur.execute('delete from prototypes where serial_number=?', (serial_number,))
        elif serial_type == 'component':
            cur.execute'delete from components where serial_number=?', (serial_number,))
        elif serial_type == 'experiment':
            cur.execute('delete from experiments where serial_number=?', (serial_number,))


def get_all_serialnumbers(db_name, serial_type):
    if test_for_database(db_name):
        conn = sqlite3.connect(db_name)
        cur = conn.cursor()
        if serial_type == 'prototype':
            cur.execute('select * from prototypes')
            return cur.fetchall()
        elif serial_type == 'component':
            cur.execute('select * from components')
            return cur.fetchall()
        elif serial_type == 'experiment':
            cur.execute('select * from experiments')
            return cur.fetchall()


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('mode', type=str, choices=['setup', 'add'], help='Mode to run script in: db setup, or adding records to a db.')
    parser.add_argument('-d', '--database', default='serial.db', type=str, help='Name for database. Defaults to "serial.db".')
    parser.add_argument('-t', '--type', default='prototype', type=str, help='Type of serial number being added. Can be either prototype, component, or experiment. Defaults to prototype. Use with add mode.')
    parser.add_argument('-s', '--serial', type=str, help='Serial number being added. Use with add mode.')
    parser.add_argument('-n', '--name', type=str, default='', help='Name associated with serial number. Use with add mode.')
    args = parser.parse_args()
    if args.mode == 'setup':
        create_database(args.database)
    elif args.mode == 'add':
        add_record(args.database, args.type, args.serial, args.name)
        